import { useState, useEffect } from "react";
import { TaskBar, Task } from "./components/TaskBar";
import { AddTaskDialog } from "./components/AddTaskDialog";
import { format, addDays, parseISO, subDays, isSameDay } from "date-fns";
import { ChevronLeft, ChevronRight, Moon, Sun, TriangleAlert } from "lucide-react";

const isLegacyAutoGeneratedTask = (task: Task) => {
  return task.id.startsWith("sync-") || task.id.startsWith("health-");
};

const DAILY_TASK_LIMIT = 8;
const DAILY_WORKLOAD_MINUTES_LIMIT = 360;
const MIN_HEALTH_MINUTES_RECOMMENDED = 45;

function App() {
  const [currentDate, setCurrentDate] = useState(new Date());
  const [tasks, setTasks] = useState<Task[]>([]);
  const [addTaskOpen, setAddTaskOpen] = useState(false);
  const [addTaskType, setAddTaskType] = useState<"workload" | "health">("workload");
  const [darkMode, setDarkMode] = useState(() => {
    const stored = localStorage.getItem("dark-mode");
    return stored ? JSON.parse(stored) : false;
  });

  // Apply dark mode class to document
  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
    localStorage.setItem("dark-mode", JSON.stringify(darkMode));
  }, [darkMode]);

  // Load tasks from localStorage on mount
  useEffect(() => {
    const storedTasks = localStorage.getItem("work-health-tasks");
    if (!storedTasks) {
      return;
    }

    try {
      const parsedTasks: Task[] = JSON.parse(storedTasks);
      const cleanedTasks = parsedTasks.filter((task) => !isLegacyAutoGeneratedTask(task));

      setTasks(cleanedTasks);

      if (cleanedTasks.length !== parsedTasks.length) {
        localStorage.setItem("work-health-tasks", JSON.stringify(cleanedTasks));
      }
    } catch {
      setTasks([]);
      localStorage.removeItem("work-health-tasks");
    }
  }, []);

  // Save tasks to localStorage
  useEffect(() => {
    if (tasks.length > 0) {
      localStorage.setItem("work-health-tasks", JSON.stringify(tasks));
    }
  }, [tasks]);

  // Filter tasks based on date and view mode
  const filteredTasks = tasks.filter((task) => {
    const taskDate = parseISO(task.date);
    return format(taskDate, "yyyy-MM-dd") === format(currentDate, "yyyy-MM-dd");
  });

  const workloadTasks = filteredTasks.filter((t) => 
    ["Assignments", "Quizzes", "Projects", "Reading", "Study Sessions", "Meetings"].includes(t.category)
  );
  
  const healthTasks = filteredTasks.filter((t) => 
    ["Exercise", "Meditation", "Meals", "Sleep", "Breaks", "Social Time"].includes(t.category)
  );

  // Calculate percentages
  const calculatePercentage = (taskList: Task[]) => {
    if (taskList.length === 0) return 100; // Health bar at 100% when no tasks
    const completedDuration = taskList.filter(t => t.completed).reduce((sum, t) => sum + t.duration, 0);
    const totalDuration = taskList.reduce((sum, t) => sum + t.duration, 0);
    return totalDuration > 0 ? Math.round((completedDuration / totalDuration) * 100) : 0;
  };

  const workloadPercentage = calculatePercentage(workloadTasks);
  const healthPercentage = calculatePercentage(healthTasks);

  const allTasksDone = filteredTasks.length > 0 && filteredTasks.every((t) => t.completed);
  const workloadMinutes = workloadTasks.reduce((sum, task) => sum + task.duration, 0);
  const healthMinutes = healthTasks.reduce((sum, task) => sum + task.duration, 0);

  const burnoutRisk =
    filteredTasks.length >= DAILY_TASK_LIMIT ||
    workloadMinutes >= DAILY_WORKLOAD_MINUTES_LIMIT ||
    (workloadMinutes >= 240 && healthMinutes < MIN_HEALTH_MINUTES_RECOMMENDED);

  const handleToggleTask = (id: string) => {
    setTasks((prev) =>
      prev.map((t) => (t.id === id ? { ...t, completed: !t.completed } : t))
    );
  };

  const handleAddTask = (type: "workload" | "health") => {
    setAddTaskType(type);
    setAddTaskOpen(true);
  };

  const handleCreateTask = (newTask: { title: string; category: string; duration: number }) => {
    const task: Task = {
      id: `custom-${Date.now()}`,
      ...newTask,
      completed: false,
      date: format(currentDate, "yyyy-MM-dd"),
    };
    setTasks((prev) => [...prev, task]);
  };

  const handlePreviousDay = () => {
    setCurrentDate((prev) => subDays(prev, 1));
  };

  const handleNextDay = () => {
    setCurrentDate((prev) => addDays(prev, 1));
  };

  const handleToday = () => {
    setCurrentDate(new Date());
  };

  const getDateLabel = () => {
    const today = new Date();
    const yesterday = subDays(today, 1);
    const tomorrow = addDays(today, 1);

    if (isSameDay(currentDate, today)) {
      return "Today";
    } else if (isSameDay(currentDate, yesterday)) {
      return "Yesterday";
    } else if (isSameDay(currentDate, tomorrow)) {
      return "Tomorrow";
    } else {
      return format(currentDate, "MMM d, yyyy");
    }
  };

  return (
    <div className="h-screen bg-gradient-to-br from-gray-50 to-gray-100 dark:from-gray-900 dark:to-gray-800 flex flex-col">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 shadow-sm px-4 py-4">
        <div className="flex items-center justify-between mb-3">
          <div className="w-10"></div>
          <h1 className="text-2xl font-bold text-center text-gray-800 dark:text-gray-100">
            Work-Health Tracker
          </h1>
          <button
            onClick={() => setDarkMode(!darkMode)}
            className="w-10 h-10 flex items-center justify-center rounded-lg bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
            aria-label="Toggle dark mode"
          >
            {darkMode ? (
              <Sun className="w-5 h-5 text-yellow-500" />
            ) : (
              <Moon className="w-5 h-5 text-gray-600" />
            )}
          </button>
        </div>
        
        {/* Date Navigation */}
        <div className="flex items-center justify-between gap-4">
          <button
            onClick={handlePreviousDay}
            className="w-10 h-10 flex items-center justify-center rounded-lg bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
            aria-label="Previous day"
          >
            <ChevronLeft className="w-5 h-5 text-gray-700 dark:text-gray-300" />
          </button>
          
          <button
            onClick={handleToday}
            className="flex-1 py-2 px-4 rounded-lg bg-blue-50 dark:bg-blue-900/20 hover:bg-blue-100 dark:hover:bg-blue-900/30 transition-colors text-center"
          >
            <span className="text-sm font-semibold text-blue-700 dark:text-blue-300">
              {getDateLabel()}
            </span>
          </button>
          
          <button
            onClick={handleNextDay}
            className="w-10 h-10 flex items-center justify-center rounded-lg bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
            aria-label="Next day"
          >
            <ChevronRight className="w-5 h-5 text-gray-700 dark:text-gray-300" />
          </button>
        </div>
      </div>

      {/* All Tasks Done Banner */}
      {allTasksDone && (
        <div className="bg-gradient-to-r from-green-500 to-blue-500 text-white px-4 py-3 text-center shadow-md">
          <div className="flex items-center justify-center gap-2">
            <span className="text-2xl">🎉</span>
            <span className="text-xl font-bold">All Tasks Done!!</span>
            <span className="text-2xl">🎉</span>
          </div>
          <p className="text-sm mt-1 opacity-90">Great work! Time to rest and recharge.</p>
        </div>
      )}

      {/* Burnout Warning Banner */}
      {burnoutRisk && (
        <div className="bg-gradient-to-r from-amber-500 to-orange-500 text-white px-4 py-3 shadow-md">
          <div className="flex items-center justify-center gap-2">
            <TriangleAlert className="w-5 h-5" />
            <span className="text-sm font-semibold">Burnout Warning</span>
          </div>
          <p className="text-xs mt-1 text-center opacity-95">
            This day looks overloaded. Consider reducing tasks or adding recovery time.
          </p>
        </div>
      )}

      {/* Main Content */}
      <div className="flex-1 grid grid-cols-2 gap-4 p-4 overflow-hidden">
        {/* Workload Bar (Left) */}
        <TaskBar
          title="Workload"
          type="workload"
          percentage={workloadPercentage}
          tasks={workloadTasks}
          onToggleTask={handleToggleTask}
          onAddTask={() => handleAddTask("workload")}
        />

        {/* Health Bar (Right) */}
        <TaskBar
          title="Health"
          type="health"
          percentage={healthPercentage}
          tasks={healthTasks}
          onToggleTask={handleToggleTask}
          onAddTask={() => handleAddTask("health")}
        />
      </div>

      {/* Add Task Dialog */}
      <AddTaskDialog
        open={addTaskOpen}
        onClose={() => setAddTaskOpen(false)}
        onAdd={handleCreateTask}
        type={addTaskType}
      />
    </div>
  );
}

export default App;